//
// Created by nathan on 16/04/20.
//

#ifndef ANDROIDOPENGLESLESSONSCPP_DODECAHEDRON_H
#define ANDROIDOPENGLESLESSONSCPP_DODECAHEDRON_H


class Dodecahedron {

};


#endif //ANDROIDOPENGLESLESSONSCPP_DODECAHEDRON_H
