//
// Created by nathan on 16/04/20.
//

#ifndef ANDROIDOPENGLESLESSONSCPP_OCTAHEDRON_H
#define ANDROIDOPENGLESLESSONSCPP_OCTAHEDRON_H


class Octahedron {

};


#endif //ANDROIDOPENGLESLESSONSCPP_OCTAHEDRON_H
