//
// Created by nathan on 28/04/20.
//

#ifndef ANDROIDOPENGLESLESSONSCPP_GLINCLUDES_H
#define ANDROIDOPENGLESLESSONSCPP_GLINCLUDES_H

#include <EGL/egl.h>
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>

#endif //ANDROIDOPENGLESLESSONSCPP_GLINCLUDES_H
